import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json
import cv2
import numpy as np
from datetime import datetime
import os
from typing import Dict, List

# Import our analysis components for live analysis
from game_analyzer import HockeyGameAnalyzer

class CoachingDashboard:
    """Streamlit-based coaching dashboard for hockey game analysis"""
    
    def __init__(self):
        self.setup_page_config()
    
    def setup_page_config(self):
        """Setup Streamlit page configuration"""
        st.set_page_config(
            page_title="🏒 Hockey Coaching Dashboard",
            page_icon="🏒",
            layout="wide",
            initial_sidebar_state="expanded"
        )
        
        # Custom CSS
        st.markdown("""
        <style>
        .main-header {
            font-size: 3em;
            color: #1f4e79;
            text-align: center;
            padding: 1em 0;
        }
        .metric-card {
            background-color: #f0f2f6;
            padding: 1em;
            border-radius: 0.5em;
            border-left: 4px solid #1f4e79;
        }
        .play-event {
            background-color: #e8f4fd;
            padding: 0.5em;
            margin: 0.2em 0;
            border-radius: 0.3em;
        }
        </style>
        """, unsafe_allow_html=True)
    
    def run(self):
        """Main dashboard application"""
        st.markdown('<h1 class="main-header">🏒 Hockey Coaching Dashboard</h1>', 
                   unsafe_allow_html=True)
        
        # Sidebar for navigation and controls
        with st.sidebar:
            st.image("https://via.placeholder.com/200x100/1f4e79/ffffff?text=HOCKEY+ANALYZER", 
                    width=200)
            
            mode = st.selectbox(
                "Select Mode",
                ["📊 Load Analysis Results", "🎥 Analyze New Game", "📈 Compare Games"]
            )
        
        if mode == "📊 Load Analysis Results":
            self.load_analysis_mode()
        elif mode == "🎥 Analyze New Game":
            self.analyze_game_mode()
        elif mode == "📈 Compare Games":
            self.compare_games_mode()
    
    def load_analysis_mode(self):
        """Load and display previous analysis results"""
        st.header("📊 Game Analysis Results")
        
        # File uploader for analysis results
        uploaded_file = st.file_uploader(
            "Upload game_analysis.json file",
            type=['json'],
            help="Upload the JSON file generated by game_analyzer.py"
        )
        
        if uploaded_file:
            try:
                analysis_data = json.load(uploaded_file)
                self.display_game_analysis(analysis_data)
            except Exception as e:
                st.error(f"Error loading analysis file: {e}")
        else:
            # Try to load from default output directory
            default_path = "analysis_output/game_analysis.json"
            if os.path.exists(default_path):
                st.info(f"Loading analysis from {default_path}")
                with open(default_path, 'r') as f:
                    analysis_data = json.load(f)
                self.display_game_analysis(analysis_data)
            else:
                st.info("Upload an analysis file or run a new game analysis to get started.")
    
    def analyze_game_mode(self):
        """Analyze a new game video"""
        st.header("🎥 Analyze New Game")
        
        with st.form("game_analysis_form"):
            video_file = st.file_uploader(
                "Upload Hockey Video",
                type=['mp4', 'avi', 'mov'],
                help="Upload a hockey game video for analysis"
            )
            
            col1, col2 = st.columns(2)
            with col1:
                max_frames = st.number_input(
                    "Max Frames to Process",
                    min_value=100,
                    max_value=10000,
                    value=600,
                    help="Limit processing for testing (600 frames ≈ 20 seconds)"
                )
            
            with col2:
                create_debug_video = st.checkbox(
                    "Create Debug Video",
                    value=True,
                    help="Generate annotated video showing detection results"
                )
            
            analyze_button = st.form_submit_button("🚀 Start Analysis", use_container_width=True)
        
        if analyze_button and video_file:
            # Save uploaded video temporarily
            temp_video_path = f"temp_video_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp4"
            with open(temp_video_path, "wb") as f:
                f.write(video_file.read())
            
            try:
                # Run analysis
                with st.spinner("🏒 Analyzing hockey game... This may take several minutes."):
                    analyzer = HockeyGameAnalyzer(output_dir="streamlit_analysis_output")
                    
                    # Create progress bar
                    progress_bar = st.progress(0)
                    status_text = st.empty()
                    
                    result = analyzer.analyze_game(
                        video_path=temp_video_path,
                        max_frames=max_frames,
                        create_debug_video=create_debug_video
                    )
                    
                    progress_bar.progress(1.0)
                    status_text.success("✅ Analysis Complete!")
                
                # Display results
                st.success("🎉 Game analysis completed successfully!")
                analysis_data = self._convert_result_to_dict(result)
                self.display_game_analysis(analysis_data)
                
                # Cleanup
                os.remove(temp_video_path)
                
            except Exception as e:
                st.error(f"Error during analysis: {e}")
                if os.path.exists(temp_video_path):
                    os.remove(temp_video_path)
    
    def display_game_analysis(self, analysis_data: Dict):
        """Display comprehensive game analysis"""
        
        # Game overview
        col1, col2, col3, col4 = st.columns(4)
        
        game_stats = analysis_data.get('game_stats', {})
        
        with col1:
            st.metric(
                "Game Duration",
                f"{analysis_data['game_info']['video_duration']:.1f}s",
                help="Total video duration analyzed"
            )
        
        with col2:
            st.metric(
                "Processing Speed",
                f"{game_stats.get('avg_fps', 0):.1f} fps",
                help="Average processing speed"
            )
        
        with col3:
            st.metric(
                "Player Detection",
                f"{game_stats.get('player_detection_rate', 0)*100:.0f}%",
                help="Percentage of frames with player detection"
            )
        
        with col4:
            st.metric(
                "Puck Detection",
                f"{game_stats.get('puck_detection_rate', 0)*100:.0f}%",
                help="Percentage of frames with puck detection"
            )
        
        # Key statistics
        st.header("📈 Key Game Statistics")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.subheader("🎯 Play Events")
            st.metric("Total Plays", game_stats.get('total_plays', 0))
            st.metric("Zone Entries", game_stats.get('zone_entries', 0))
            st.metric("Turnovers", game_stats.get('turnovers', 0))
            st.metric("Shots", game_stats.get('shots', 0))
        
        with col2:
            st.subheader("👥 Team Performance")
            team_confidence = game_stats.get('team_confidence', 0)
            st.metric("Team ID Confidence", f"{team_confidence*100:.0f}%")
            
            # Team information
            teams = analysis_data.get('team_info', {}).get('teams', {})
            for team_id, team_data in teams.items():
                if hasattr(team_data, 'team_name'):
                    # team_data is a TeamColors dataclass
                    st.write(f"**Team {team_id + 1}**: {team_data.team_name}")
                    st.write(f"Jersey Color: RGB{team_data.primary_color}")
                else:
                    # team_data is a dictionary
                    st.write(f"**Team {team_id + 1}**: {team_data.get('team_name', 'Unknown')}")
                    if 'primary_color' in team_data:
                        color = team_data['primary_color']
                        st.write(f"Jersey Color: RGB{color}")
        
        with col3:
            st.subheader("⚙️ System Performance")
            st.metric("Frames Processed", f"{game_stats.get('total_frames', 0):,}")
            st.metric("Processing Time", f"{game_stats.get('processing_time', 0):.1f}s")
            
            # Real-time factor
            video_duration = analysis_data['game_info']['video_duration']
            processing_time = game_stats.get('processing_time', 1)
            realtime_factor = video_duration / processing_time
            st.metric("Real-time Factor", f"{realtime_factor:.1f}x")
        
        # Play events analysis
        self.display_play_events_analysis(analysis_data)
        
        # Zone analysis
        self.display_zone_analysis(analysis_data)
        
        # Timeline view
        self.display_timeline_analysis(analysis_data)
    
    def display_play_events_analysis(self, analysis_data: Dict):
        """Display play events analysis"""
        st.header("🎭 Play Events Analysis")
        
        play_events = analysis_data.get('play_events', [])
        
        if not play_events:
            st.info("No play events detected in this analysis.")
            return
        
        # Convert to DataFrame
        df_plays = pd.DataFrame(play_events)
        
        col1, col2 = st.columns(2)
        
        with col1:
            # Play type distribution
            play_counts = df_plays['play_type'].value_counts()
            
            fig_plays = px.bar(
                x=play_counts.values,
                y=play_counts.index,
                orientation='h',
                title="Play Type Distribution",
                labels={'x': 'Count', 'y': 'Play Type'}
            )
            fig_plays.update_layout(height=400)
            st.plotly_chart(fig_plays, use_container_width=True)
        
        with col2:
            # Zone distribution
            if 'zone' in df_plays.columns:
                zone_counts = df_plays['zone'].value_counts()
                
                fig_zones = px.pie(
                    values=zone_counts.values,
                    names=zone_counts.index,
                    title="Plays by Zone"
                )
                st.plotly_chart(fig_zones, use_container_width=True)
        
        # Timeline of events
        if 'timestamp' in df_plays.columns:
            st.subheader("📅 Event Timeline")
            
            # Create timeline chart
            fig_timeline = px.scatter(
                df_plays,
                x='timestamp',
                y='play_type',
                color='team_id',
                size='confidence',
                hover_data=['zone', 'description'],
                title="Play Events Over Time"
            )
            fig_timeline.update_layout(height=400)
            st.plotly_chart(fig_timeline, use_container_width=True)
        
        # Recent events table
        st.subheader("📋 Recent Play Events")
        
        # Show last 20 events
        recent_events = df_plays.tail(20)[['timestamp', 'play_type', 'zone', 'description', 'confidence']]
        recent_events['timestamp'] = recent_events['timestamp'].apply(lambda x: f"{x:.1f}s")
        recent_events['confidence'] = recent_events['confidence'].apply(lambda x: f"{x:.2f}")
        
        st.dataframe(recent_events, use_container_width=True)
    
    def display_zone_analysis(self, analysis_data: Dict):
        """Display zone-based analysis"""
        st.header("🏟️ Zone Analysis")
        
        zone_analysis = analysis_data.get('zone_analysis', {})
        play_distribution = zone_analysis.get('play_distribution', {})
        
        if not play_distribution:
            st.info("No zone analysis data available.")
            return
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("📊 Zone Activity")
            zones_data = play_distribution.get('zones', {})
            if zones_data:
                zones_df = pd.DataFrame(list(zones_data.items()), columns=['Zone', 'Activity'])
                
                fig_zone_activity = px.bar(
                    zones_df,
                    x='Zone',
                    y='Activity',
                    title="Activity by Zone"
                )
                st.plotly_chart(fig_zone_activity, use_container_width=True)
        
        with col2:
            st.subheader("🔄 Possession Changes")
            possession_changes = play_distribution.get('possession_changes', 0)
            zone_entries = play_distribution.get('zone_entries', 0)
            
            metrics_data = {
                'Metric': ['Possession Changes', 'Zone Entries'],
                'Count': [possession_changes, zone_entries]
            }
            
            fig_metrics = px.bar(
                metrics_data,
                x='Metric',
                y='Count',
                title="Key Metrics"
            )
            st.plotly_chart(fig_metrics, use_container_width=True)
    
    def display_timeline_analysis(self, analysis_data: Dict):
        """Display timeline-based analysis"""
        st.header("⏱️ Game Timeline")
        
        play_events = analysis_data.get('play_events', [])
        
        if not play_events:
            st.info("No timeline data available.")
            return
        
        # Create time-based aggregations
        df_plays = pd.DataFrame(play_events)
        
        if 'timestamp' in df_plays.columns:
            # Group by 30-second intervals
            df_plays['time_interval'] = (df_plays['timestamp'] // 30) * 30
            
            # Count events per interval
            timeline_data = df_plays.groupby(['time_interval', 'play_type']).size().reset_index(name='count')
            
            # Create stacked area chart
            fig_timeline = px.area(
                timeline_data,
                x='time_interval',
                y='count',
                color='play_type',
                title="Play Activity Over Time (30s intervals)"
            )
            
            fig_timeline.update_layout(
                xaxis_title="Time (seconds)",
                yaxis_title="Number of Events",
                height=400
            )
            
            st.plotly_chart(fig_timeline, use_container_width=True)
            
            # Game flow analysis
            st.subheader("🌊 Game Flow Analysis")
            
            # Calculate intensity (events per minute)
            df_plays['minute'] = df_plays['timestamp'] // 60
            intensity = df_plays.groupby('minute').size().reset_index(name='events_per_minute')
            
            fig_intensity = px.line(
                intensity,
                x='minute',
                y='events_per_minute',
                title="Game Intensity (Events per Minute)"
            )
            
            st.plotly_chart(fig_intensity, use_container_width=True)
    
    def compare_games_mode(self):
        """Compare multiple game analyses"""
        st.header("📈 Compare Games")
        st.info("🚧 Game comparison feature coming soon! Upload multiple analysis files to compare team performance across games.")
        
        # Placeholder for future implementation
        st.markdown("""
        **Planned Features:**
        - Compare team performance across multiple games
        - Track improvement over time
        - Identify patterns and trends
        - Export comparison reports
        """)
    
    def _convert_result_to_dict(self, result) -> Dict:
        """Convert GameAnalysisResult to dictionary for display"""
        from dataclasses import asdict
        
        return {
            'game_info': result.game_info,
            'game_stats': asdict(result.game_stats),
            'team_info': result.team_info,
            'zone_analysis': result.zone_analysis,
            'play_events': [self._play_event_to_dict(pe) for pe in result.play_events]
        }
    
    def _play_event_to_dict(self, play_event) -> Dict:
        """Convert PlayEvent to dictionary"""
        return {
            'play_type': play_event.play_type.value,
            'timestamp': play_event.timestamp,
            'frame_number': play_event.frame_number,
            'zone': play_event.zone.value,
            'team_id': play_event.team_id,
            'description': play_event.description,
            'confidence': play_event.confidence
        }

def main():
    """Main entry point for Streamlit app"""
    dashboard = CoachingDashboard()
    dashboard.run()

if __name__ == "__main__":
    main()